server:
  port: 8080


spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.ckevuiz8guuf.ap-northeast-2.rds.amazonaws.com/todayhouse?autoReconnect=true
    username: admin
    password: Rndlstjd112!
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB



cloud:
  aws:
    s3:
      bucket: bali-todayhouse
    credentials:
      access-key: AKIA4GS24BHYWNQMB7PS
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
