server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.ckevuiz8guuf.ap-northeast-2.rds.amazonaws.com/test?autoReconnect=true # 변경해주세요
    username: admin
    password: Rndlstjd112!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전




